# Generated by Django 4.0.1 on 2022-02-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMercosulNomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=5000)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('act_type', models.CharField(max_length=255)),
                ('act_number', models.CharField(max_length=255)),
                ('act_year', models.IntegerField()),
            ],
        ),
    ]
