# Generated by Django 4.0.1 on 2022-02-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivojson',
            name='Nomenclaturas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ncms', to='api.commonmercosulnomenclature'),
        ),
    ]
