# Generated by Django 4.0.1 on 2022-02-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_arquivojson_nomenclaturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivojson',
            name='Nomenclaturas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
